= Venus Application API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[auth]]
== 인증/인가

=== 로그인

==== 성공

operation::login_success[snippets='http-request,http-response']

[[member]]
== 회원

=== 회원 가입

==== 성공

operation::signupMember_success[snippets='http-request,http-response']

==== 입력값이 잘못됐을 때

operation::signupMember_failedByMultipleInvalidInput[snippets='http-response']

==== 이미 가입된 이메일일 때

operation::signupMember_failedByDuplicateEmail[snippets='http-response']

==== 이미 가입된 닉네임일 때

operation::signupMember_failedByDuplicateNickname[snippets='http-response']

==== 재입력한 비밀번호가 다를 때

operation::signupMember_failedByReconfirmPasswordUnmatch[snippets='http-response']

=== 회원 수정

=== 성공

operation::updateMember_success['http-request,http-response']

=== 회원 조회

==== 회원 장르 조회

operation::myPageRead_success['http-request,http-response']

==== 회원 id 조회

operation::fetchMemberId_success['http-request,http-response']

[[movie]]
=== 메인 페이지

==== 메인 페이지 조회

operation::fetchMovieListByLatest_success[snippets='http-response']

operation::fetchMovieListByPopular_success[snippets='http-response']

operation::fetchMovieListByGenre_success[snippets='http-response']

=== 상세 페이지

operation::userLoginHasInterestGenre_success[snippets='http-response']

operation::recentHeartSimilarCrewMovie_success[snippets='http-response']

operation::searchMovie_success[snippets='http-request,http-response']

==== 상세 페이지 조회

operation::fetchMovieDetail_success[snippets='http-response']

// operation::fetchMovieComment_success[snippets='http-request,http-response']

operation::fetchMovieDetailCrews_success[snippets='http-request,http-response']

operation::fetchMovieDetailGenres_success[snippets='http-request,http-response']

=== 검색 페이지

=== 코멘트

==== 코멘트 등록

operation::createMovieComment_success[snippets='http-request,http-response']

==== 코멘트 등록 실패 (해당 영화 코멘트에 현재 멤버가 이미 존재합니다.)

operation::createMovieComment_failed_duplicated_404[snippets='http-request,http-response']

==== 코멘트 수정

operation::updateMovieComment_success[snippets='http-request,http-response']

=== 코멘트 전체 조회 (비로그인)

operation::fetchMovieCommentList_success[snippets='http-request,http-response']

=== 코멘트 전체 조회 (로그인)

operation::fetchMovieCommentList_withSession_success[snippets='http-request,http-response']

=== 코멘트 단일 조회 (로그인)

operation::fetchMyMovieComment_withSession_success[snippets='http-request,http-response']

=== 코멘트 삭제

operation::deleteMovieComment_success[snippets='http-request,http-response']

=== 코멘트 좋아요

operation::movie_comment_like_increment_success[snippets='http-request,http-response']

=== 코멘트 좋아요 취소

operation::movie_comment_unlike_decrement_success[snippets='http-request,http-response']

[[image]]
== 이미지

=== 이미지 업로드

// operation::uploadMemberProfileImage_success[snippets='http-request,http-response']

== 채팅

=== 그룹 채팅

==== 그룹 채팅 생성

operation::createGroupChat_success[snippets='http-request,http-response']

==== 그룹 채팅 가입

operation::joinGroupChat_success[snippets='http-request,http-response']

==== 그룹 채팅 가입 여부

operation::unJoinMemberCheckGroupChatJoin_success[snippets='http-request,http-response']

operation::joinMemberCheckGroupChatJoin_success[snippets='http-request,http-response']

operation::memberCheckNotExistGroupChatJoin_success[snippets='http-request,http-response']

=== 일대일 채팅

==== 일대일 채팅 생성

operation::createOneononeChatroom_success[snippets='http-request,http-response']

==== 일대일 채팅 목록 조회

operation::getOneononeChatroom_success[snippets='http-response']